### ISSUE TITLE
In what port does the TeamCity server run?

### ISSUE THREAD

**Issue by miparnisari** [rodm/teamcity-vagrant#1]
Isn't there something missing in the `Vagrantfile`, like a port forward? I know that TC runs on port 8111 by default but I cannot connect to it from my host machine.

Also, what is the username/password combination to connect to the machine using VirtualBox?

![login](https://cloud.githubusercontent.com/assets/5374887/16248153/dce965bc-37e3-11e6-9627-a10a51a8ff14.png)

**Comment by rodm** [comment]
In the Vagrantfile the server is given the IP address 192.168.80.10 you should be able then to enter the URL http://192.168.80.10:8111/teamcity to access the server.

The user and group setup to run TeamCity is given the username, teamcity, but I don't think this can be used to login directly. You can login as vagrant then use sudo to become root then use su to become the teamcity user, a bit convoluted but I didn't think direct access was needed. What are you wanting to do?

**Comment by rodm** [comment]
I've updated the readme with info on accessing the server.

**Comment by miparnisari** [comment]
Thanks for that! I was able to view the site now.

What I was trying to do was login via GUI to the server.

**Comment by miparnisari** [comment]
Hey sorry to bother you again. How do I instruct the server to use the build agent 1? I've upped the agent through `vagrant up agent01` and in the server went to `Agents > Agent push` and configured it but the connection fails.

![agent](https://cloud.githubusercontent.com/assets/5374887/16548989/0ff77cb0-4170-11e6-9748-4f3288ee1ba0.png)

**Comment by rodm** [comment]
The agent vm is provisioned using the setup-agent script, this downloads
and installs the agent software, so using the 'Agent Push' option isn't
needed. You should check the 'Unauthorized' tab for the agent and authorize
it after it has started and connected to the server.
